theme: jekyll-theme-cayman
title: Multi-agent Indoor Navigation
name: Multi-agent Indoor Navigation
description: A Real-world Multi-agent Indoor Navigation Benchmark for Cooperative Learning
show_downloads: true
is_project_page: true
markdown: kramdown
github:
  zip_url: https://drive.google.com/file/d/1H3fvyPi_OoXJfzV0HzK-Gix5fiizdM4Z/view?usp=sharing
  tar_url: https://main-dataset.github.io/bar.tar
  repository_url: https://github.com/ZhuFengdaaa/MAIN
